with open('src/components/Manifiesto.jsx', 'w', encoding='utf-8') as f:
    f.write(
'import { useState, useEffect } from ' + chr(39) + 'react' + chr(39) + ';\n'
'import { Users, Search, CheckCircle, XCircle, Clock } from ' + chr(39) + 'lucide-react' + chr(39) + ';\n'
'import axios from ' + chr(39) + 'axios' + chr(39) + ';\n'
'\n'
'export default function Manifiesto() {\n'
'  const [schedules, setSchedules] = useState([]);\n'
'  const [selected, setSelected] = useState(null);\n'
'  const [bookings, setBookings] = useState([]);\n'
'  const [loading, setLoading] = useState(false);\n'
'\n'
'  useEffect(() => {\n'
'    axios.get(' + chr(39) + 'http://localhost:8000/api/v1/routes/search' + chr(39) + ', {\n'
'      method: ' + chr(39) + 'POST' + chr(39) + '\n'
'    }).catch(() => {});\n'
'    const today = new Date().toISOString().split(' + chr(39) + 'T' + chr(39) + ')[0];\n'
'    axios.post(' + chr(39) + 'http://localhost:8000/api/v1/routes/search' + chr(39) + ', {\n'
'      origin: ' + chr(39) + 'La Paz' + chr(39) + ', destination: ' + chr(39) + 'Cochabamba' + chr(39) + ', date: today, passengers: 1\n'
'    }).then(r => setSchedules(r.data.results || [])).catch(() => {});\n'
'  }, []);\n'
'\n'
'  const loadBookings = async (scheduleId) => {\n'
'    setSelected(scheduleId);\n'
'    setLoading(true);\n'
'    try {\n'
'      const r = await axios.get(' + chr(39) + 'http://localhost:8000/api/v1/bookings/schedule/' + chr(39) + ' + scheduleId);\n'
'      setBookings(r.data.bookings || []);\n'
'    } catch { setBookings([]); }\n'
'    finally { setLoading(false); }\n'
'  };\n'
'\n'
'  const STATUS_ICON = {\n'
'    confirmed: <CheckCircle size={16} className=' + chr(34) + 'text-green-500' + chr(34) + '/>,\n'
'    pending: <Clock size={16} className=' + chr(34) + 'text-amber-500' + chr(34) + '/>,\n'
'    cancelled: <XCircle size={16} className=' + chr(34) + 'text-red-500' + chr(34) + '/>,\n'
'    used: <CheckCircle size={16} className=' + chr(34) + 'text-blue-500' + chr(34) + '/>,\n'
'  };\n'
'\n'
'  return (\n'
'    <div>\n'
'      <h2 className=' + chr(34) + 'text-xl font-bold text-[#1B2A6B] mb-6' + chr(34) + '>Manifiesto de Pasajeros</h2>\n'
'      <div className=' + chr(34) + 'grid grid-cols-3 gap-6' + chr(34) + '>\n'
'        <div className=' + chr(34) + 'col-span-1' + chr(34) + '>\n'
'          <div className=' + chr(34) + 'card' + chr(34) + '>\n'
'            <h3 className=' + chr(34) + 'font-semibold text-gray-700 mb-3 flex items-center gap-2' + chr(34) + '><Search size={16}/> Horarios del día</h3>\n'
'            <div className=' + chr(34) + 'flex flex-col gap-2' + chr(34) + '>\n'
'              {schedules.length === 0 && <p className=' + chr(34) + 'text-gray-400 text-sm' + chr(34) + '>No hay horarios cargados</p>}\n'
'              {schedules.map(s => (\n'
'                <button key={s.id} onClick={() => loadBookings(s.id)}\n'
'                  className={' + chr(34) + 'text-left p-3 rounded-lg border-2 transition-all text-sm ' + chr(34) + ' + (selected === s.id ? ' + chr(39) + 'border-[#1B2A6B] bg-[#f0f4ff]' + chr(39) + ' : ' + chr(39) + 'border-gray-200 hover:border-gray-300' + chr(39) + ')}>\n'
'                  <p className=' + chr(34) + 'font-semibold text-[#1B2A6B]' + chr(34) + '>{s.origin} → {s.destination}</p>\n'
'                  <p className=' + chr(34) + 'text-gray-500 text-xs' + chr(34) + '>{s.company} · {new Date(s.departure_time).toLocaleTimeString()}</p>\n'
'                  <p className=' + chr(34) + 'text-xs text-gray-400' + chr(34) + '>{s.available_seats} asientos libres</p>\n'
'                </button>\n'
'              ))}\n'
'            </div>\n'
'          </div>\n'
'        </div>\n'
'        <div className=' + chr(34) + 'col-span-2' + chr(34) + '>\n'
'          <div className=' + chr(34) + 'card' + chr(34) + '>\n'
'            <div className=' + chr(34) + 'flex items-center justify-between mb-4' + chr(34) + '>\n'
'              <h3 className=' + chr(34) + 'font-semibold text-gray-700 flex items-center gap-2' + chr(34) + '><Users size={16}/> Lista de Pasajeros {bookings.length > 0 && <span className=' + chr(34) + 'badge-active' + chr(34) + '>({bookings.length})</span>}</h3>\n'
'            </div>\n'
'            {!selected && <p className=' + chr(34) + 'text-gray-400 text-center py-8' + chr(34) + '>Selecciona un horario para ver el manifiesto</p>}\n'
'            {loading && <p className=' + chr(34) + 'text-gray-400 text-center py-8' + chr(34) + '>Cargando...</p>}\n'
'            {!loading && selected && bookings.length === 0 && <p className=' + chr(34) + 'text-gray-400 text-center py-8' + chr(34) + '>No hay pasajeros en este horario</p>}\n'
'            {bookings.length > 0 && (\n'
'              <table className=' + chr(34) + 'w-full text-sm' + chr(34) + '>\n'
'                <thead><tr className=' + chr(34) + 'bg-gray-50 text-gray-600' + chr(34) + '>\n'
'                  <th className=' + chr(34) + 'px-3 py-2 text-left' + chr(34) + '>Asiento</th>\n'
'                  <th className=' + chr(34) + 'px-3 py-2 text-left' + chr(34) + '>Pasajero</th>\n'
'                  <th className=' + chr(34) + 'px-3 py-2 text-left' + chr(34) + '>CI</th>\n'
'                  <th className=' + chr(34) + 'px-3 py-2 text-left' + chr(34) + '>Total</th>\n'
'                  <th className=' + chr(34) + 'px-3 py-2 text-left' + chr(34) + '>Estado</th>\n'
'                </tr></thead>\n'
'                <tbody>\n'
'                  {bookings.map(b => (\n'
'                    <tr key={b.id} className=' + chr(34) + 'border-t border-gray-100 hover:bg-gray-50' + chr(34) + '>\n'
'                      <td className=' + chr(34) + 'px-3 py-2 font-bold text-[#1B2A6B]' + chr(34) + '>{b.seat_number || "-"}</td>\n'
'                      <td className=' + chr(34) + 'px-3 py-2' + chr(34) + '>{b.passenger_name}</td>\n'
'                      <td className=' + chr(34) + 'px-3 py-2 text-gray-500' + chr(34) + '>{b.passenger_ci}</td>\n'
'                      <td className=' + chr(34) + 'px-3 py-2 font-semibold' + chr(34) + '>Bs. {b.total_price}</td>\n'
'                      <td className=' + chr(34) + 'px-3 py-2' + chr(34) + '><span className=' + chr(34) + 'flex items-center gap-1' + chr(34) + '>{STATUS_ICON[b.status]} {b.status}</span></td>\n'
'                    </tr>\n'
'                  ))}\n'
'                </tbody>\n'
'              </table>\n'
'            )}\n'
'          </div>\n'
'        </div>\n'
'      </div>\n'
'    </div>\n'
'  );\n'
'}\n'
    )
print('OK: Manifiesto.jsx')