with open('src/components/Reportes.jsx', 'w', encoding='utf-8') as f:
    f.write(
'import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, PieChart, Pie, Cell } from ' + chr(39) + 'recharts' + chr(39) + ';\n'
'import { TrendingUp, DollarSign, Users, Bus } from ' + chr(39) + 'lucide-react' + chr(39) + ';\n'
'\n'
'const VENTAS_MES = [\n'
'  { mes: ' + chr(39) + 'Ene' + chr(39) + ', ventas: 245, ingresos: 32450 },\n'
'  { mes: ' + chr(39) + 'Feb' + chr(39) + ', ventas: 312, ingresos: 41280 },\n'
'  { mes: ' + chr(39) + 'Mar' + chr(39) + ', ventas: 289, ingresos: 38200 },\n'
'  { mes: ' + chr(39) + 'Abr' + chr(39) + ', ventas: 421, ingresos: 55650 },\n'
'  { mes: ' + chr(39) + 'May' + chr(39) + ', ventas: 387, ingresos: 51100 },\n'
'  { mes: ' + chr(39) + 'Jun' + chr(39) + ', ventas: 456, ingresos: 60230 },\n'
'];\n'
'\n'
'const POR_EMPRESA = [\n'
'  { name: ' + chr(39) + 'Bolivia Bus Express' + chr(39) + ', value: 35, color: ' + chr(39) + '#1B2A6B' + chr(39) + ' },\n'
'  { name: ' + chr(39) + 'Trans Copacabana' + chr(39) + ', value: 28, color: ' + chr(39) + '#D4AF37' + chr(39) + ' },\n'
'  { name: ' + chr(39) + 'Flota Boliviana' + chr(39) + ', value: 22, color: ' + chr(39) + '#C8102E' + chr(39) + ' },\n'
'  { name: ' + chr(39) + 'Flota Yunguena' + chr(39) + ', value: 15, color: ' + chr(39) + '#10B981' + chr(39) + ' },\n'
'];\n'
'\n'
'const STATS = [\n'
'  { label: ' + chr(39) + 'Ventas del mes' + chr(39) + ', value: ' + chr(39) + '421' + chr(39) + ', icon: TrendingUp, color: ' + chr(39) + 'bg-blue-50 text-blue-600' + chr(39) + ' },\n'
'  { label: ' + chr(39) + 'Ingresos del mes' + chr(39) + ', value: ' + chr(39) + 'Bs. 55,650' + chr(39) + ', icon: DollarSign, color: ' + chr(39) + 'bg-green-50 text-green-600' + chr(39) + ' },\n'
'  { label: ' + chr(39) + 'Pasajeros activos' + chr(39) + ', value: ' + chr(39) + '1,284' + chr(39) + ', icon: Users, color: ' + chr(39) + 'bg-purple-50 text-purple-600' + chr(39) + ' },\n'
'  { label: ' + chr(39) + 'Buses en ruta' + chr(39) + ', value: ' + chr(39) + '3' + chr(39) + ', icon: Bus, color: ' + chr(39) + 'bg-amber-50 text-amber-600' + chr(39) + ' },\n'
'];\n'
'\n'
'export default function Reportes() {\n'
'  return (\n'
'    <div>\n'
'      <h2 className=' + chr(34) + 'text-xl font-bold text-[#1B2A6B] mb-6' + chr(34) + '>Reportes de Ventas</h2>\n'
'      <div className=' + chr(34) + 'grid grid-cols-4 gap-4 mb-6' + chr(34) + '>\n'
'        {STATS.map(s => (\n'
'          <div key={s.label} className=' + chr(34) + 'card flex items-center gap-4' + chr(34) + '>\n'
'            <div className={' + chr(34) + 'w-12 h-12 rounded-xl flex items-center justify-center ' + chr(34) + ' + s.color}>\n'
'              <s.icon size={22}/>\n'
'            </div>\n'
'            <div>\n'
'              <p className=' + chr(34) + 'text-2xl font-bold text-gray-800' + chr(34) + '>{s.value}</p>\n'
'              <p className=' + chr(34) + 'text-xs text-gray-500' + chr(34) + '>{s.label}</p>\n'
'            </div>\n'
'          </div>\n'
'        ))}\n'
'      </div>\n'
'      <div className=' + chr(34) + 'grid grid-cols-3 gap-6' + chr(34) + '>\n'
'        <div className=' + chr(34) + 'card col-span-2' + chr(34) + '>\n'
'          <h3 className=' + chr(34) + 'font-semibold text-gray-700 mb-4' + chr(34) + '>Ventas e Ingresos por Mes</h3>\n'
'          <ResponsiveContainer width=' + chr(34) + '100%' + chr(34) + ' height={300}>\n'
'            <BarChart data={VENTAS_MES}>\n'
'              <CartesianGrid strokeDasharray=' + chr(34) + '3 3' + chr(34) + '/>\n'
'              <XAxis dataKey=' + chr(34) + 'mes' + chr(34) + '/>\n'
'              <YAxis/>\n'
'              <Tooltip/>\n'
'              <Legend/>\n'
'              <Bar dataKey=' + chr(34) + 'ventas' + chr(34) + ' fill=' + chr(34) + '#1B2A6B' + chr(34) + ' name=' + chr(34) + 'Pasajes Vendidos' + chr(34) + '/>\n'
'              <Bar dataKey=' + chr(34) + 'ingresos' + chr(34) + ' fill=' + chr(34) + '#D4AF37' + chr(34) + ' name=' + chr(34) + 'Ingresos (Bs.)' + chr(34) + '/>\n'
'            </BarChart>\n'
'          </ResponsiveContainer>\n'
'        </div>\n'
'        <div className=' + chr(34) + 'card' + chr(34) + '>\n'
'          <h3 className=' + chr(34) + 'font-semibold text-gray-700 mb-4' + chr(34) + '>Ventas por Empresa</h3>\n'
'          <ResponsiveContainer width=' + chr(34) + '100%' + chr(34) + ' height={200}>\n'
'            <PieChart>\n'
'              <Pie data={POR_EMPRESA} dataKey=' + chr(34) + 'value' + chr(34) + ' nameKey=' + chr(34) + 'name' + chr(34) + ' cx=' + chr(34) + '50%' + chr(34) + ' cy=' + chr(34) + '50%' + chr(34) + ' outerRadius={80} label>\n'
'                {POR_EMPRESA.map((e, i) => <Cell key={i} fill={e.color}/>)}\n'
'              </Pie>\n'
'              <Tooltip/>\n'
'            </PieChart>\n'
'          </ResponsiveContainer>\n'
'          <div className=' + chr(34) + 'flex flex-col gap-2 mt-2' + chr(34) + '>\n'
'            {POR_EMPRESA.map(e => (\n'
'              <div key={e.name} className=' + chr(34) + 'flex items-center gap-2 text-sm' + chr(34) + '>\n'
'                <span className=' + chr(34) + 'w-3 h-3 rounded-full' + chr(34) + ' style={{ background: e.color }}></span>\n'
'                <span className=' + chr(34) + 'text-gray-600' + chr(34) + '>{e.name}</span>\n'
'                <span className=' + chr(34) + 'ml-auto font-semibold' + chr(34) + '>{e.value}%</span>\n'
'              </div>\n'
'            ))}\n'
'          </div>\n'
'        </div>\n'
'      </div>\n'
'    </div>\n'
'  );\n'
'}\n'
    )
print('OK: Reportes.jsx')