with open('src/components/TrackingMap.jsx', 'w', encoding='utf-8') as f:
    f.write(
'import { useEffect, useState, useRef } from ' + chr(39) + 'react' + chr(39) + ';\n'
'import { MapContainer, TileLayer, Marker, Popup, useMap } from ' + chr(39) + 'react-leaflet' + chr(39) + ';\n'
'import L from ' + chr(39) + 'leaflet' + chr(39) + ';\n'
'import ' + chr(39) + 'leaflet/dist/leaflet.css' + chr(39) + ';\n'
'import { WS_URL, getLatestLocations } from ' + chr(39) + '../api' + chr(39) + ';\n'
'\n'
'const BUS_ICON = L.divIcon({\n'
'  html: ' + chr(39) + '<div style="font-size:28px;filter:drop-shadow(2px 2px 2px rgba(0,0,0,0.5))">🚌</div>' + chr(39) + ',\n'
'  iconSize: [36, 36],\n'
'  iconAnchor: [18, 18],\n'
'  className: ' + chr(39) + chr(39) + ',\n'
'});\n'
'\n'
'const BUS_COLORS = { normal: ' + chr(39) + '#3B82F6' + chr(39) + ', semicama: ' + chr(39) + '#8B5CF6' + chr(39) + ', cama: ' + chr(39) + '#D97706' + chr(39) + ' };\n'
'\n'
'function BusMarker({ bus }) {\n'
'  const icon = L.divIcon({\n'
'    html: ' + chr(39) + '<div style="font-size:32px;filter:drop-shadow(2px 2px 3px rgba(0,0,0,0.6));animation:pulse 2s infinite">🚌</div>' + chr(39) + ',\n'
'    iconSize: [40, 40],\n'
'    iconAnchor: [20, 20],\n'
'    className: ' + chr(39) + chr(39) + ',\n'
'  });\n'
'  return (\n'
'    <Marker position={[bus.latitude, bus.longitude]} icon={icon}>\n'
'      <Popup>\n'
'        <div style={{ minWidth: ' + chr(39) + '180px' + chr(39) + ' }}>\n'
'          <p style={{ fontWeight: ' + chr(39) + 'bold' + chr(39) + ', color: ' + chr(39) + '#1B2A6B' + chr(39) + ', marginBottom: 4 }}>{bus.company}</p>\n'
'          <p style={{ fontSize: 12 }}>🚌 Placa: <strong>{bus.plate}</strong></p>\n'
'          <p style={{ fontSize: 12 }}>📍 Tipo: <strong style={{ textTransform: ' + chr(39) + 'capitalize' + chr(39) + ' }}>{bus.bus_type}</strong></p>\n'
'          <p style={{ fontSize: 12 }}>⚡ Velocidad: <strong>{bus.speed_kmh} km/h</strong></p>\n'
'          <p style={{ fontSize: 12 }}>🔴 Estado: <strong>{bus.status}</strong></p>\n'
'          <p style={{ fontSize: 10, color: ' + chr(39) + 'gray' + chr(39) + ', marginTop: 4 }}>{new Date(bus.timestamp).toLocaleTimeString()}</p>\n'
'        </div>\n'
'      </Popup>\n'
'    </Marker>\n'
'  );\n'
'}\n'
'\n'
'export default function TrackingMap() {\n'
'  const [buses, setBuses] = useState({});\n'
'  const [connected, setConnected] = useState(false);\n'
'  const wsRef = useRef(null);\n'
'\n'
'  useEffect(() => {\n'
'    getLatestLocations().then(r => {\n'
'      const map = {};\n'
'      r.data.buses.forEach(b => { map[b.bus_id] = b; });\n'
'      setBuses(map);\n'
'    }).catch(() => {});\n'
'\n'
'    const ws = new WebSocket(WS_URL);\n'
'    wsRef.current = ws;\n'
'    ws.onopen = () => { setConnected(true); console.log(' + chr(39) + 'WS conectado' + chr(39) + '); };\n'
'    ws.onclose = () => { setConnected(false); };\n'
'    ws.onmessage = (e) => {\n'
'      const data = JSON.parse(e.data);\n'
'      if (data.type === ' + chr(39) + 'location_update' + chr(39) + ') {\n'
'        setBuses(prev => ({ ...prev, [data.bus_id]: data }));\n'
'      }\n'
'    };\n'
'    return () => ws.close();\n'
'  }, []);\n'
'\n'
'  const busList = Object.values(buses);\n'
'  const center = busList.length > 0\n'
'    ? [busList[0].latitude, busList[0].longitude]\n'
'    : [-16.5000, -68.1500];\n'
'\n'
'  return (\n'
'    <div className=' + chr(34) + 'flex flex-col h-full' + chr(34) + '>\n'
'      <div className=' + chr(34) + 'flex items-center justify-between mb-4' + chr(34) + '>\n'
'        <h2 className=' + chr(34) + 'text-xl font-bold text-[#1B2A6B]' + chr(34) + '>Rastreo de Flotas en Tiempo Real</h2>\n'
'        <div className=' + chr(34) + 'flex items-center gap-4' + chr(34) + '>\n'
'          <span className={' + chr(34) + 'flex items-center gap-2 text-sm font-semibold px-3 py-1 rounded-full ' + chr(34) + ' + (connected ? ' + chr(39) + 'bg-green-100 text-green-700' + chr(39) + ' : ' + chr(39) + 'bg-red-100 text-red-700' + chr(39) + ')}>\n'
'            <span className={' + chr(34) + 'w-2 h-2 rounded-full ' + chr(34) + ' + (connected ? ' + chr(39) + 'bg-green-500 animate-pulse' + chr(39) + ' : ' + chr(39) + 'bg-red-500' + chr(39) + ')}></span>\n'
'            {connected ? ' + chr(39) + 'EN VIVO' + chr(39) + ' : ' + chr(39) + 'Desconectado' + chr(39) + '}\n'
'          </span>\n'
'          <span className=' + chr(34) + 'text-sm text-gray-500' + chr(34) + '>{busList.length} buses activos</span>\n'
'        </div>\n'
'      </div>\n'
'      <div className=' + chr(34) + 'flex gap-4 mb-4' + chr(34) + '>\n'
'        {busList.map(b => (\n'
'          <div key={b.bus_id} className=' + chr(34) + 'flex items-center gap-2 bg-white rounded-lg px-3 py-2 shadow-sm border border-gray-100 text-sm' + chr(34) + '>\n'
'            <span>🚌</span>\n'
'            <div>\n'
'              <p className=' + chr(34) + 'font-semibold text-[#1B2A6B] text-xs' + chr(34) + '>{b.company}</p>\n'
'              <p className=' + chr(34) + 'text-gray-400 text-xs' + chr(34) + '>{b.speed_kmh} km/h</p>\n'
'            </div>\n'
'          </div>\n'
'        ))}\n'
'      </div>\n'
'      <div className=' + chr(34) + 'flex-1 rounded-xl overflow-hidden shadow-lg border border-gray-200' + chr(34) + ' style={{ minHeight: ' + chr(39) + '500px' + chr(39) + ' }}>\n'
'        <MapContainer center={center} zoom={7} style={{ height: ' + chr(39) + '100%' + chr(39) + ', width: ' + chr(39) + '100%' + chr(39) + ', minHeight: ' + chr(39) + '500px' + chr(39) + ' }}>\n'
'          <TileLayer\n'
'            attribution=' + chr(39) + chr(39) + '\n'
'            url=' + chr(34) + 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png' + chr(34) + '\n'
'          />\n'
'          {busList.map(b => <BusMarker key={b.bus_id} bus={b}/>)}\n'
'        </MapContainer>\n'
'      </div>\n'
'    </div>\n'
'  );\n'
'}\n'
    )
print('OK: TrackingMap.jsx')