with open('src/components/Horarios.jsx', 'w', encoding='utf-8') as f:
    f.write('\n'.join([
        'import { useState, useEffect } from ' + chr(39) + 'react' + chr(39) + ';',
        'import { Calendar, Plus, Trash2, Clock, Bus, MapPin } from ' + chr(39) + 'lucide-react' + chr(39) + ';',
        'import axios from ' + chr(39) + 'axios' + chr(39) + ';',
        '',
        'const API = ' + chr(39) + 'http://localhost:8000/api/v1' + chr(39) + ';',
        '',
        'const STATUS_STYLE = {',
        '  active: ' + chr(39) + 'bg-green-100 text-green-700' + chr(39) + ',',
        '  cancelled: ' + chr(39) + 'bg-red-100 text-red-700' + chr(39) + ',',
        '  completed: ' + chr(39) + 'bg-gray-100 text-gray-600' + chr(39) + ',',
        '};',
        '',
        'export default function Horarios() {',
        '  const [schedules, setSchedules] = useState([]);',
        '  const [buses, setBuses] = useState([]);',
        '  const [routes, setRoutes] = useState([]);',
        '  const [showForm, setShowForm] = useState(false);',
        '  const [loading, setLoading] = useState(true);',
        '  const [form, setForm] = useState({',
        '    route_id: ' + chr(39) + chr(39) + ', bus_id: ' + chr(39) + chr(39) + ',',
        '    departure_time: ' + chr(39) + chr(39) + ',',
        '    price_normal: 80, price_semicama: 120, price_cama: 160, terminal_fee: 2.50',
        '  });',
        '',
        '  const load = async () => {',
        '    setLoading(true);',
        '    try {',
        '      const [s, b, r] = await Promise.all([',
        '        axios.get(API + ' + chr(39) + '/schedules/' + chr(39) + '),',
        '        axios.get(API + ' + chr(39) + '/schedules/buses' + chr(39) + '),',
        '        axios.get(API + ' + chr(39) + '/schedules/routes' + chr(39) + '),',
        '      ]);',
        '      setSchedules(s.data.schedules || []);',
        '      setBuses(b.data.buses || []);',
        '      setRoutes(r.data.routes || []);',
        '    } catch(e) { console.error(e); }',
        '    finally { setLoading(false); }',
        '  };',
        '',
        '  useEffect(() => { load(); }, []);',
        '',
        '  const handleCreate = async () => {',
        '    if (!form.route_id || !form.bus_id || !form.departure_time) return;',
        '    try {',
        '      await axios.post(API + ' + chr(39) + '/schedules/' + chr(39) + ', form);',
        '      setShowForm(false);',
        '      load();',
        '    } catch(e) { alert(e.response?.data?.detail || ' + chr(39) + 'Error al crear horario' + chr(39) + '); }',
        '  };',
        '',
        '  const handleCancel = async (id) => {',
        '    if (!confirm(' + chr(39) + chr(39) + chr(99) + chr(97) + chr(110) + chr(99) + chr(101) + chr(108) + chr(97) + chr(114) + chr(39) + chr(39) + ')) return;',
        '    try {',
        '      await axios.delete(API + ' + chr(39) + '/schedules/' + chr(39) + ' + id);',
        '      load();',
        '    } catch(e) { alert(' + chr(39) + 'Error al cancelar' + chr(39) + '); }',
        '  };',
        '',
        '  return (',
        '    <div>',
        '      <div className=' + chr(34) + 'flex items-center justify-between mb-6' + chr(34) + '>',
        '        <h2 className=' + chr(34) + 'text-xl font-bold text-[#1B2A6B]' + chr(34) + '>Gestión de Horarios</h2>',
        '        <button onClick={() => setShowForm(!showForm)} className=' + chr(34) + 'btn-primary flex items-center gap-2' + chr(34) + '>',
        '          <Plus size={16}/> Nuevo Horario',
        '        </button>',
        '      </div>',
        '      {showForm && (',
        '        <div className=' + chr(34) + 'card mb-6 border-2 border-[#1B2A6B]' + chr(34) + '>',
        '          <h3 className=' + chr(34) + 'font-bold text-[#1B2A6B] mb-4 flex items-center gap-2' + chr(34) + '><Calendar size={18}/> Crear Nuevo Horario</h3>',
        '          <div className=' + chr(34) + 'grid grid-cols-2 gap-4' + chr(34) + '>',
        '            <div>',
        '              <label className=' + chr(34) + 'text-sm font-semibold text-gray-600 block mb-1' + chr(34) + '>Ruta</label>',
        '              <select className=' + chr(34) + 'w-full border border-gray-300 rounded-lg px-3 py-2 text-sm' + chr(34) + ' value={form.route_id} onChange={e=>setForm({...form,route_id:e.target.value})}>',
        '                <option value=' + chr(34) + chr(34) + '>Seleccionar ruta...</option>',
        '                {routes.map(r => <option key={r.id} value={r.id}>{r.origin} → {r.destination} ({r.duration_hours}h)</option>)}',
        '              </select>',
        '            </div>',
        '            <div>',
        '              <label className=' + chr(34) + 'text-sm font-semibold text-gray-600 block mb-1' + chr(34) + '>Bus</label>',
        '              <select className=' + chr(34) + 'w-full border border-gray-300 rounded-lg px-3 py-2 text-sm' + chr(34) + ' value={form.bus_id} onChange={e=>setForm({...form,bus_id:e.target.value})}>',
        '                <option value=' + chr(34) + chr(34) + '>Seleccionar bus...</option>',
        '                {buses.map(b => <option key={b.id} value={b.id}>{b.company} — {b.plate} ({b.bus_type})</option>)}',
        '              </select>',
        '            </div>',
        '            <div>',
        '              <label className=' + chr(34) + 'text-sm font-semibold text-gray-600 block mb-1' + chr(34) + '>Fecha y Hora de Salida</label>',
        '              <input type=' + chr(34) + 'datetime-local' + chr(34) + ' className=' + chr(34) + 'w-full border border-gray-300 rounded-lg px-3 py-2 text-sm' + chr(34) + ' value={form.departure_time} onChange={e=>setForm({...form,departure_time:e.target.value})}/>',
        '            </div>',
        '            <div>',
        '              <label className=' + chr(34) + 'text-sm font-semibold text-gray-600 block mb-1' + chr(34) + '>Derecho Terminal (Bs.)</label>',
        '              <input type=' + chr(34) + 'number' + chr(34) + ' className=' + chr(34) + 'w-full border border-gray-300 rounded-lg px-3 py-2 text-sm' + chr(34) + ' value={form.terminal_fee} onChange={e=>setForm({...form,terminal_fee:+e.target.value})}/>',
        '            </div>',
        '            <div>',
        '              <label className=' + chr(34) + 'text-sm font-semibold text-gray-600 block mb-1' + chr(34) + '>Precio Normal (Bs.)</label>',
        '              <input type=' + chr(34) + 'number' + chr(34) + ' className=' + chr(34) + 'w-full border border-gray-300 rounded-lg px-3 py-2 text-sm' + chr(34) + ' value={form.price_normal} onChange={e=>setForm({...form,price_normal:+e.target.value})}/>',
        '            </div>',
        '            <div>',
        '              <label className=' + chr(34) + 'text-sm font-semibold text-gray-600 block mb-1' + chr(34) + '>Precio Semicama (Bs.)</label>',
        '              <input type=' + chr(34) + 'number' + chr(34) + ' className=' + chr(34) + 'w-full border border-gray-300 rounded-lg px-3 py-2 text-sm' + chr(34) + ' value={form.price_semicama} onChange={e=>setForm({...form,price_semicama:+e.target.value})}/>',
        '            </div>',
        '            <div>',
        '              <label className=' + chr(34) + 'text-sm font-semibold text-gray-600 block mb-1' + chr(34) + '>Precio Cama (Bs.)</label>',
        '              <input type=' + chr(34) + 'number' + chr(34) + ' className=' + chr(34) + 'w-full border border-gray-300 rounded-lg px-3 py-2 text-sm' + chr(34) + ' value={form.price_cama} onChange={e=>setForm({...form,price_cama:+e.target.value})}/>',
        '            </div>',
        '          </div>',
        '          <div className=' + chr(34) + 'flex gap-3 mt-4' + chr(34) + '>',
        '            <button onClick={handleCreate} className=' + chr(34) + 'btn-primary' + chr(34) + '>Crear Horario</button>',
        '            <button onClick={() => setShowForm(false)} className=' + chr(34) + 'px-4 py-2 border border-gray-300 rounded-lg text-sm' + chr(34) + '>Cancelar</button>',
        '          </div>',
        '        </div>',
        '      )}',
        '      {loading ? <p className=' + chr(34) + 'text-center py-8 text-gray-400' + chr(34) + '>Cargando horarios...</p> : (',
        '        <div className=' + chr(34) + 'card' + chr(34) + '>',
        '          <table className=' + chr(34) + 'w-full text-sm' + chr(34) + '>',
        '            <thead><tr className=' + chr(34) + 'bg-gray-50 text-gray-600 text-left' + chr(34) + '>',
        '              <th className=' + chr(34) + 'px-3 py-3' + chr(34) + '>Ruta</th>',
        '              <th className=' + chr(34) + 'px-3 py-3' + chr(34) + '>Empresa</th>',
        '              <th className=' + chr(34) + 'px-3 py-3' + chr(34) + '>Salida</th>',
        '              <th className=' + chr(34) + 'px-3 py-3' + chr(34) + '>Tipo</th>',
        '              <th className=' + chr(34) + 'px-3 py-3' + chr(34) + '>Asientos</th>',
        '              <th className=' + chr(34) + 'px-3 py-3' + chr(34) + '>Precio</th>',
        '              <th className=' + chr(34) + 'px-3 py-3' + chr(34) + '>Estado</th>',
        '              <th className=' + chr(34) + 'px-3 py-3' + chr(34) + '>Acción</th>',
        '            </tr></thead>',
        '            <tbody>',
        '              {schedules.map(s => (',
        '                <tr key={s.id} className=' + chr(34) + 'border-t border-gray-100 hover:bg-gray-50' + chr(34) + '>',
        '                  <td className=' + chr(34) + 'px-3 py-3' + chr(34) + '>',
        '                    <p className=' + chr(34) + 'font-semibold text-[#1B2A6B]' + chr(34) + '>{s.origin} → {s.destination}</p>',
        '                  </td>',
        '                  <td className=' + chr(34) + 'px-3 py-3 text-gray-600' + chr(34) + '>{s.company}</td>',
        '                  <td className=' + chr(34) + 'px-3 py-3' + chr(34) + '>',
        '                    <p>{new Date(s.departure_time).toLocaleDateString()}</p>',
        '                    <p className=' + chr(34) + 'text-gray-400 text-xs' + chr(34) + '>{new Date(s.departure_time).toLocaleTimeString()}</p>',
        '                  </td>',
        '                  <td className=' + chr(34) + 'px-3 py-3 capitalize' + chr(34) + '>{s.bus_type}</td>',
        '                  <td className=' + chr(34) + 'px-3 py-3' + chr(34) + '>',
        '                    <span className=' + chr(34) + 'text-green-600 font-semibold' + chr(34) + '>{s.seats_available}</span>',
        '                    <span className=' + chr(34) + 'text-gray-400' + chr(34) + '>/{s.seats_total}</span>',
        '                  </td>',
        '                  <td className=' + chr(34) + 'px-3 py-3 font-semibold' + chr(34) + '>Bs. {s.price_normal}</td>',
        '                  <td className=' + chr(34) + 'px-3 py-3' + chr(34) + '>',
        '                    <span className={' + chr(34) + 'text-xs px-2 py-1 rounded-full font-semibold ' + chr(34) + ' + (STATUS_STYLE[s.status] || ' + chr(39) + 'bg-gray-100' + chr(39) + ')}>{s.status}</span>',
        '                  </td>',
        '                  <td className=' + chr(34) + 'px-3 py-3' + chr(34) + '>',
        '                    {s.status === ' + chr(39) + 'active' + chr(39) + ' && (',
        '                      <button onClick={() => handleCancel(s.id)} className=' + chr(34) + 'flex items-center gap-1 text-red-500 hover:text-red-700 text-xs' + chr(34) + '>',
        '                        <Trash2 size={14}/> Cancelar',
        '                      </button>',
        '                    )}',
        '                  </td>',
        '                </tr>',
        '              ))}',
        '            </tbody>',
        '          </table>',
        '        </div>',
        '      )}',
        '    </div>',
        '  );',
        '}',
    ]) + '\n')
print('OK: Horarios.jsx')