with open('src/App.jsx', 'w', encoding='utf-8') as f:
    f.write(
'import { useState } from ' + chr(39) + 'react' + chr(39) + ';\n'
'import Navbar from ' + chr(39) + './components/Navbar' + chr(39) + ';\n'
'import TrackingMap from ' + chr(39) + './components/TrackingMap' + chr(39) + ';\n'
'import Empresas from ' + chr(39) + './components/Empresas' + chr(39) + ';\n'
'import Manifiesto from ' + chr(39) + './components/Manifiesto' + chr(39) + ';\n'
'import Reportes from ' + chr(39) + './components/Reportes' + chr(39) + ';\n'
'\n'
'export default function App() {\n'
'  const [page, setPage] = useState(' + chr(39) + 'mapa' + chr(39) + ');\n'
'\n'
'  const PAGES = {\n'
'    mapa: <TrackingMap/>,\n'
'    empresas: <Empresas/>,\n'
'    horarios: <div className=' + chr(34) + 'text-center py-20 text-gray-400' + chr(34) + '>Módulo de Horarios — En desarrollo</div>,\n'
'    manifiesto: <Manifiesto/>,\n'
'    reportes: <Reportes/>,\n'
'  };\n'
'\n'
'  return (\n'
'    <div className=' + chr(34) + 'flex bg-gray-100 min-h-screen' + chr(34) + '>\n'
'      <Navbar active={page} onNav={setPage}/>\n'
'      <main className=' + chr(34) + 'ml-64 flex-1 p-8' + chr(34) + '>\n'
'        {PAGES[page]}\n'
'      </main>\n'
'    </div>\n'
'  );\n'
'}\n'
    )
print('OK: App.jsx')