with open('src/components/Login.jsx', 'w', encoding='utf-8') as f:
    f.write(
'import { useState } from ' + chr(39) + 'react' + chr(39) + ';\n'
'import { Bus, Lock, Mail, AlertCircle } from ' + chr(39) + 'lucide-react' + chr(39) + ';\n'
'import axios from ' + chr(39) + 'axios' + chr(39) + ';\n'
'\n'
'export default function Login({ onLogin }) {\n'
'  const [form, setForm] = useState({ email: ' + chr(39) + chr(39) + ', password: ' + chr(39) + chr(39) + ' });\n'
'  const [error, setError] = useState(' + chr(39) + chr(39) + ');\n'
'  const [loading, setLoading] = useState(false);\n'
'\n'
'  const handleLogin = async (e) => {\n'
'    e.preventDefault();\n'
'    setLoading(true); setError(' + chr(39) + chr(39) + ');\n'
'    try {\n'
'      const res = await axios.post(' + chr(39) + 'http://localhost:8000/api/v1/auth/login' + chr(39) + ', form);\n'
'      const token = res.data.access_token;\n'
'      const me = await axios.get(' + chr(39) + 'http://localhost:8000/api/v1/auth/me' + chr(39) + ', {\n'
'        headers: { Authorization: ' + chr(34) + 'Bearer ' + chr(34) + ' + token }\n'
'      });\n'
'      if (!me.data.is_admin) {\n'
'        setError(' + chr(39) + 'Acceso denegado. Solo administradores.' + chr(39) + ');\n'
'        return;\n'
'      }\n'
'      localStorage.setItem(' + chr(39) + 'bb_token' + chr(39) + ', token);\n'
'      localStorage.setItem(' + chr(39) + 'bb_user' + chr(39) + ', JSON.stringify(me.data));\n'
'      onLogin(me.data, token);\n'
'    } catch (e) {\n'
'      setError(e.response?.data?.detail || ' + chr(39) + 'Credenciales incorrectas' + chr(39) + ');\n'
'    } finally { setLoading(false); }\n'
'  };\n'
'\n'
'  return (\n'
'    <div className=' + chr(34) + 'min-h-screen bg-gradient-to-br from-[#1B2A6B] to-[#0d1a4a] flex items-center justify-center px-4' + chr(34) + '>\n'
'      <div className=' + chr(34) + 'bg-white rounded-2xl shadow-2xl p-8 w-full max-w-md' + chr(34) + '>\n'
'        <div className=' + chr(34) + 'text-center mb-8' + chr(34) + '>\n'
'          <div className=' + chr(34) + 'w-16 h-16 bg-[#1B2A6B] rounded-2xl flex items-center justify-center mx-auto mb-4' + chr(34) + '>\n'
'            <Bus size={32} className=' + chr(34) + 'text-[#D4AF37]' + chr(34) + '/>\n'
'          </div>\n'
'          <h1 className=' + chr(34) + 'text-2xl font-bold text-[#1B2A6B]' + chr(34) + '>Bolivia Bus</h1>\n'
'          <p className=' + chr(34) + 'text-gray-500 text-sm mt-1' + chr(34) + '>Panel Administrativo — Solo personal autorizado</p>\n'
'        </div>\n'
'        <form onSubmit={handleLogin} className=' + chr(34) + 'flex flex-col gap-4' + chr(34) + '>\n'
'          <div>\n'
'            <label className=' + chr(34) + 'text-sm font-semibold text-gray-700 mb-1 flex items-center gap-1' + chr(34) + '><Mail size={14}/> Correo electrónico</label>\n'
'            <input type=' + chr(34) + 'email' + chr(34) + ' className=' + chr(34) + 'w-full border border-gray-300 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-[#1B2A6B]' + chr(34) + '\n'
'              placeholder=' + chr(34) + 'admin@boliviabus.bo' + chr(34) + ' value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/>\n'
'          </div>\n'
'          <div>\n'
'            <label className=' + chr(34) + 'text-sm font-semibold text-gray-700 mb-1 flex items-center gap-1' + chr(34) + '><Lock size={14}/> Contraseña</label>\n'
'            <input type=' + chr(34) + 'password' + chr(34) + ' className=' + chr(34) + 'w-full border border-gray-300 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-[#1B2A6B]' + chr(34) + '\n'
'              placeholder=' + chr(34) + '••••••••' + chr(34) + ' value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>\n'
'          </div>\n'
'          {error && (\n'
'            <div className=' + chr(34) + 'flex items-center gap-2 bg-red-50 border border-red-200 rounded-lg px-4 py-3 text-red-600 text-sm' + chr(34) + '>\n'
'              <AlertCircle size={16}/> {error}\n'
'            </div>\n'
'          )}\n'
'          <button type=' + chr(34) + 'submit' + chr(34) + ' disabled={loading}\n'
'            className=' + chr(34) + 'btn-primary w-full py-3 flex items-center justify-center gap-2 mt-2' + chr(34) + '>\n'
'            <Lock size={16}/> {loading ? ' + chr(39) + 'Verificando...' + chr(39) + ' : ' + chr(39) + 'Ingresar al Panel' + chr(39) + '}\n'
'          </button>\n'
'        </form>\n'
'        <div className=' + chr(34) + 'mt-6 p-3 bg-gray-50 rounded-lg text-center' + chr(34) + '>\n'
'          <p className=' + chr(34) + 'text-xs text-gray-400' + chr(34) + '>Demo: admin@boliviabus.bo / admin1234</p>\n'
'        </div>\n'
'      </div>\n'
'    </div>\n'
'  );\n'
'}\n'
    )
print('OK: Login.jsx')