with open('src/App.jsx', 'w', encoding='utf-8') as f:
    f.write(
'import { useState, useEffect } from ' + chr(39) + 'react' + chr(39) + ';\n'
'import Navbar from ' + chr(39) + './components/Navbar' + chr(39) + ';\n'
'import TrackingMap from ' + chr(39) + './components/TrackingMap' + chr(39) + ';\n'
'import Empresas from ' + chr(39) + './components/Empresas' + chr(39) + ';\n'
'import Manifiesto from ' + chr(39) + './components/Manifiesto' + chr(39) + ';\n'
'import Reportes from ' + chr(39) + './components/Reportes' + chr(39) + ';\n'
'import Login from ' + chr(39) + './components/Login' + chr(39) + ';\n'
'\n'
'export default function App() {\n'
'  const [page, setPage] = useState(' + chr(39) + 'mapa' + chr(39) + ');\n'
'  const [user, setUser] = useState(null);\n'
'  const [token, setToken] = useState(null);\n'
'\n'
'  useEffect(() => {\n'
'    const savedToken = localStorage.getItem(' + chr(39) + 'bb_token' + chr(39) + ');\n'
'    const savedUser = localStorage.getItem(' + chr(39) + 'bb_user' + chr(39) + ');\n'
'    if (savedToken && savedUser) {\n'
'      setToken(savedToken);\n'
'      setUser(JSON.parse(savedUser));\n'
'    }\n'
'  }, []);\n'
'\n'
'  const handleLogin = (userData, userToken) => {\n'
'    setUser(userData);\n'
'    setToken(userToken);\n'
'  };\n'
'\n'
'  const handleLogout = () => {\n'
'    localStorage.removeItem(' + chr(39) + 'bb_token' + chr(39) + ');\n'
'    localStorage.removeItem(' + chr(39) + 'bb_user' + chr(39) + ');\n'
'    setUser(null);\n'
'    setToken(null);\n'
'  };\n'
'\n'
'  if (!user) return <Login onLogin={handleLogin}/>;\n'
'\n'
'  const PAGES = {\n'
'    mapa: <TrackingMap/>,\n'
'    empresas: <Empresas/>,\n'
'    horarios: <div className=' + chr(34) + 'text-center py-20 text-gray-400 text-lg' + chr(34) + '>Módulo de Horarios — En desarrollo</div>,\n'
'    manifiesto: <Manifiesto/>,\n'
'    reportes: <Reportes/>,\n'
'  };\n'
'\n'
'  return (\n'
'    <div className=' + chr(34) + 'flex bg-gray-100 min-h-screen' + chr(34) + '>\n'
'      <Navbar active={page} onNav={setPage}/>\n'
'      <main className=' + chr(34) + 'ml-64 flex-1 p-8' + chr(34) + '>\n'
'        <div className=' + chr(34) + 'flex items-center justify-between mb-6' + chr(34) + '>\n'
'          <div className=' + chr(34) + 'text-sm text-gray-500' + chr(34) + '>Bienvenido, <span className=' + chr(34) + 'font-semibold text-[#1B2A6B]' + chr(34) + '>{user.full_name}</span></div>\n'
'          <button onClick={handleLogout} className=' + chr(34) + 'text-sm text-red-500 hover:text-red-700 flex items-center gap-1' + chr(34) + '>Cerrar sesión</button>\n'
'        </div>\n'
'        {PAGES[page]}\n'
'      </main>\n'
'    </div>\n'
'  );\n'
'}\n'
    )
print('OK: App.jsx actualizado')