with open('src/components/Empresas.jsx', 'w', encoding='utf-8') as f:
    f.write(
'import { useState } from ' + chr(39) + 'react' + chr(39) + ';\n'
'import { Bus, Phone, Building2, CheckCircle, XCircle } from ' + chr(39) + 'lucide-react' + chr(39) + ';\n'
'\n'
'const EMPRESAS_DEMO = [\n'
'  { id: 1, name: ' + chr(39) + 'Bolivia Bus Express' + chr(39) + ', ruc: ' + chr(39) + '1234567890' + chr(39) + ', phone: ' + chr(39) + '70012345' + chr(39) + ', buses: 3, tipo: ' + chr(39) + 'Semicama' + chr(39) + ', active: true },\n'
'  { id: 2, name: ' + chr(39) + 'Trans Copacabana' + chr(39) + ', ruc: ' + chr(39) + '0987654321' + chr(39) + ', phone: ' + chr(39) + '70098765' + chr(39) + ', buses: 2, tipo: ' + chr(39) + 'Cama' + chr(39) + ', active: true },\n'
'  { id: 3, name: ' + chr(39) + 'Flota Boliviana' + chr(39) + ', ruc: ' + chr(39) + '1122334455' + chr(39) + ', phone: ' + chr(39) + '70011223' + chr(39) + ', buses: 5, tipo: ' + chr(39) + 'Normal' + chr(39) + ', active: true },\n'
'  { id: 4, name: ' + chr(39) + 'Todo Turismo' + chr(39) + ', ruc: ' + chr(39) + '5544332211' + chr(39) + ', phone: ' + chr(39) + '70055443' + chr(39) + ', buses: 1, tipo: ' + chr(39) + 'Cama' + chr(39) + ', active: false },\n'
'  { id: 5, name: ' + chr(39) + 'Flota Yunguena' + chr(39) + ', ruc: ' + chr(39) + '6677889900' + chr(39) + ', phone: ' + chr(39) + '70066778' + chr(39) + ', buses: 4, tipo: ' + chr(39) + 'Semicama' + chr(39) + ', active: true },\n'
'];\n'
'\n'
'export default function Empresas() {\n'
'  const [empresas, setEmpresas] = useState(EMPRESAS_DEMO);\n'
'  const [showForm, setShowForm] = useState(false);\n'
'  const [form, setForm] = useState({ name: ' + chr(39) + chr(39) + ', ruc: ' + chr(39) + chr(39) + ', phone: ' + chr(39) + chr(39) + ', tipo: ' + chr(39) + 'Normal' + chr(39) + ' });\n'
'\n'
'  const handleAdd = () => {\n'
'    if (!form.name || !form.ruc) return;\n'
'    setEmpresas([...empresas, { ...form, id: Date.now(), buses: 0, active: true }]);\n'
'    setForm({ name: ' + chr(39) + chr(39) + ', ruc: ' + chr(39) + chr(39) + ', phone: ' + chr(39) + chr(39) + ', tipo: ' + chr(39) + 'Normal' + chr(39) + ' });\n'
'    setShowForm(false);\n'
'  };\n'
'\n'
'  const toggleActive = (id) => {\n'
'    setEmpresas(empresas.map(e => e.id === id ? { ...e, active: !e.active } : e));\n'
'  };\n'
'\n'
'  return (\n'
'    <div>\n'
'      <div className=' + chr(34) + 'flex items-center justify-between mb-6' + chr(34) + '>\n'
'        <h2 className=' + chr(34) + 'text-xl font-bold text-[#1B2A6B]' + chr(34) + '>Empresas de Flotas</h2>\n'
'        <button onClick={() => setShowForm(!showForm)} className=' + chr(34) + 'btn-primary flex items-center gap-2' + chr(34) + '>\n'
'          <Bus size={16}/> Nueva Empresa\n'
'        </button>\n'
'      </div>\n'
'      {showForm && (\n'
'        <div className=' + chr(34) + 'card mb-6 border-2 border-[#1B2A6B]' + chr(34) + '>\n'
'          <h3 className=' + chr(34) + 'font-bold text-[#1B2A6B] mb-4' + chr(34) + '>Registrar nueva empresa</h3>\n'
'          <div className=' + chr(34) + 'grid grid-cols-2 gap-4' + chr(34) + '>\n'
'            <div><label className=' + chr(34) + 'text-sm font-semibold text-gray-600 block mb-1' + chr(34) + '>Nombre</label>\n'
'            <input className=' + chr(34) + 'w-full border border-gray-300 rounded-lg px-3 py-2 text-sm' + chr(34) + ' value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div>\n'
'            <div><label className=' + chr(34) + 'text-sm font-semibold text-gray-600 block mb-1' + chr(34) + '>RUC / NIT</label>\n'
'            <input className=' + chr(34) + 'w-full border border-gray-300 rounded-lg px-3 py-2 text-sm' + chr(34) + ' value={form.ruc} onChange={e=>setForm({...form,ruc:e.target.value})}/></div>\n'
'            <div><label className=' + chr(34) + 'text-sm font-semibold text-gray-600 block mb-1' + chr(34) + '>Teléfono</label>\n'
'            <input className=' + chr(34) + 'w-full border border-gray-300 rounded-lg px-3 py-2 text-sm' + chr(34) + ' value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div>\n'
'            <div><label className=' + chr(34) + 'text-sm font-semibold text-gray-600 block mb-1' + chr(34) + '>Tipo de Bus</label>\n'
'            <select className=' + chr(34) + 'w-full border border-gray-300 rounded-lg px-3 py-2 text-sm' + chr(34) + ' value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}>\n'
'              <option>Normal</option><option>Semicama</option><option>Cama</option>\n'
'            </select></div>\n'
'          </div>\n'
'          <div className=' + chr(34) + 'flex gap-3 mt-4' + chr(34) + '>\n'
'            <button onClick={handleAdd} className=' + chr(34) + 'btn-primary' + chr(34) + '>Guardar</button>\n'
'            <button onClick={() => setShowForm(false)} className=' + chr(34) + 'px-4 py-2 border border-gray-300 rounded-lg text-sm' + chr(34) + '>Cancelar</button>\n'
'          </div>\n'
'        </div>\n'
'      )}\n'
'      <div className=' + chr(34) + 'grid grid-cols-1 gap-4' + chr(34) + '>\n'
'        {empresas.map(e => (\n'
'          <div key={e.id} className=' + chr(34) + 'card flex items-center gap-4' + chr(34) + '>\n'
'            <div className=' + chr(34) + 'w-12 h-12 rounded-xl bg-[#1B2A6B] flex items-center justify-center flex-shrink-0' + chr(34) + '>\n'
'              <Bus size={24} className=' + chr(34) + 'text-[#D4AF37]' + chr(34) + '/>\n'
'            </div>\n'
'            <div className=' + chr(34) + 'flex-1' + chr(34) + '>\n'
'              <div className=' + chr(34) + 'flex items-center gap-2' + chr(34) + '>\n'
'                <p className=' + chr(34) + 'font-bold text-[#1B2A6B]' + chr(34) + '>{e.name}</p>\n'
'                <span className={e.active ? ' + chr(39) + 'badge-active' + chr(39) + ' : ' + chr(39) + 'badge-inactive' + chr(39) + '}>{e.active ? ' + chr(39) + 'Activa' + chr(39) + ' : ' + chr(39) + 'Inactiva' + chr(39) + '}</span>\n'
'              </div>\n'
'              <div className=' + chr(34) + 'flex gap-4 text-sm text-gray-500 mt-1' + chr(34) + '>\n'
'                <span className=' + chr(34) + 'flex items-center gap-1' + chr(34) + '><Building2 size={12}/> RUC: {e.ruc}</span>\n'
'                <span className=' + chr(34) + 'flex items-center gap-1' + chr(34) + '><Phone size={12}/> {e.phone}</span>\n'
'                <span className=' + chr(34) + 'flex items-center gap-1' + chr(34) + '><Bus size={12}/> {e.buses} buses · {e.tipo}</span>\n'
'              </div>\n'
'            </div>\n'
'            <button onClick={() => toggleActive(e.id)} className={' + chr(34) + 'flex items-center gap-1 text-sm px-3 py-1 rounded-lg ' + chr(34) + ' + (e.active ? ' + chr(39) + 'text-red-600 hover:bg-red-50' + chr(39) + ' : ' + chr(39) + 'text-green-600 hover:bg-green-50' + chr(39) + ')}>\n'
'              {e.active ? <><XCircle size={14}/> Desactivar</> : <><CheckCircle size={14}/> Activar</>}\n'
'            </button>\n'
'          </div>\n'
'        ))}\n'
'      </div>\n'
'    </div>\n'
'  );\n'
'}\n'
    )
print('OK: Empresas.jsx')