with open('src/components/TrackingMap.jsx', 'w', encoding='utf-8') as f:
    f.write('\n'.join([
        'import { useEffect, useState, useRef } from ' + chr(39) + 'react' + chr(39) + ';',
        'import { MapContainer, TileLayer, Marker, Popup } from ' + chr(39) + 'react-leaflet' + chr(39) + ';',
        'import L from ' + chr(39) + 'leaflet' + chr(39) + ';',
        'import ' + chr(39) + 'leaflet/dist/leaflet.css' + chr(39) + ';',
        'import { WS_URL, getLatestLocations } from ' + chr(39) + '../api' + chr(39) + ';',
        '',
        'const COMPANY_STYLES = {',
        '  "Bolivia Bus Express": { bg: "#1B2A6B", accent: "#D4AF37", label: "BBE", shape: "diamond" },',
        '  "Trans Copacabana":    { bg: "#C8102E", accent: "#FFFFFF", label: "TC",  shape: "circle"  },',
        '  "Flota Boliviana":     { bg: "#007A33", accent: "#F4D03F", label: "FB",  shape: "square"  },',
        '};',
        '',
        'const TYPE_EMOJI = { normal: "🚌", semicama: "🚎", cama: "🛌" };',
        '',
        'function createBusIcon(bus) {',
        '  const style = COMPANY_STYLES[bus.company] || { bg: "#555", accent: "#fff", label: "BUS", shape: "circle" };',
        '  const emoji = TYPE_EMOJI[bus.bus_type] || "🚌";',
        '  const isMoving = bus.speed_kmh > 0;',
        '',
        '  const shapes = {',
        '    diamond: <polygon points="28,4 52,28 28,52 4,28" fill="" stroke="" stroke-width="3"/>,',
        '    circle:  <circle cx="28" cy="28" r="24" fill="" stroke="" stroke-width="3"/>,',
        '    square:  <rect x="4" y="4" width="48" height="48" rx="8" fill="" stroke="" stroke-width="3"/>,',
        '  };',
        '',
        '  const pulse = isMoving ? ',
        '    <circle cx="28" cy="28" r="26" fill="none" stroke="" stroke-width="2" opacity="0.6">',
        '      <animate attributeName="r" from="26" to="38" dur="1.5s" repeatCount="indefinite"/>',
        '      <animate attributeName="opacity" from="0.6" to="0" dur="1.5s" repeatCount="indefinite"/>',
        '    </circle> : "";',
        '',
        '  const svg = <svg xmlns="http://www.w3.org/2000/svg" width="56" height="72" viewBox="0 0 56 72">',
        '    ',
        '    ',
        '    <text x="28" y="24" text-anchor="middle" font-size="16" font-family="Arial"></text>',
        '    <text x="28" y="38" text-anchor="middle" font-size="8" font-weight="bold" fill="" font-family="Arial"></text>',
        '    <text x="28" y="48" text-anchor="middle" font-size="6" fill="" font-family="Arial"></text>',
        '    <polygon points="22,54 34,54 28,66" fill=""/>',
        '  </svg>;',
        '',
        '  return L.divIcon({',
        '    html: svg,',
        '    iconSize: [56, 72],',
        '    iconAnchor: [28, 66],',
        '    className: "",',
        '  });',
        '}',
        '',
        'function BusMarker({ bus }) {',
        '  const icon = createBusIcon(bus);',
        '  const style = COMPANY_STYLES[bus.company] || { bg: "#555", accent: "#fff" };',
        '  return (',
        '    <Marker position={[bus.latitude, bus.longitude]} icon={icon}>',
        '      <Popup>',
        '        <div style={{ minWidth: 200, fontFamily: "Arial" }}>',
        '          <div style={{ background: style.bg, color: style.accent, padding: "8px 12px", borderRadius: "8px 8px 0 0", marginBottom: 8 }}>',
        '            <p style={{ fontWeight: "bold", fontSize: 14, margin: 0 }}>{bus.company}</p>',
        '            <p style={{ fontSize: 11, margin: 0, opacity: 0.8 }}>Placa: {bus.plate}</p>',
        '          </div>',
        '          <div style={{ padding: "0 4px" }}>',
        '            <p style={{ fontSize: 12, margin: "4px 0" }}>🚌 Tipo: <strong style={{ textTransform: "capitalize" }}>{bus.bus_type}</strong></p>',
        '            <p style={{ fontSize: 12, margin: "4px 0" }}>⚡ Velocidad: <strong>{bus.speed_kmh} km/h</strong></p>',
        '            <p style={{ fontSize: 12, margin: "4px 0" }}>📍 Estado: <strong>{bus.status}</strong></p>',
        '            <p style={{ fontSize: 12, margin: "4px 0" }}>📍 Lat: {bus.latitude?.toFixed(4)} | Lng: {bus.longitude?.toFixed(4)}</p>',
        '            <p style={{ fontSize: 10, color: "gray", marginTop: 6 }}>{new Date(bus.timestamp).toLocaleTimeString()}</p>',
        '          </div>',
        '        </div>',
        '      </Popup>',
        '    </Marker>',
        '  );',
        '}',
        '',
        'export default function TrackingMap() {',
        '  const [buses, setBuses] = useState({});',
        '  const [connected, setConnected] = useState(false);',
        '  const wsRef = useRef(null);',
        '',
        '  useEffect(() => {',
        '    getLatestLocations().then(r => {',
        '      const map = {};',
        '      r.data.buses.forEach(b => { map[b.bus_id] = b; });',
        '      setBuses(map);',
        '    }).catch(() => {});',
        '    const ws = new WebSocket(WS_URL);',
        '    wsRef.current = ws;',
        '    ws.onopen = () => setConnected(true);',
        '    ws.onclose = () => setConnected(false);',
        '    ws.onmessage = (e) => {',
        '      const data = JSON.parse(e.data);',
        '      if (data.type === "location_update") {',
        '        setBuses(prev => ({ ...prev, [data.bus_id]: data }));',
        '      }',
        '    };',
        '    return () => ws.close();',
        '  }, []);',
        '',
        '  const busList = Object.values(buses);',
        '  const center = busList.length > 0 ? [busList[0].latitude, busList[0].longitude] : [-16.5, -68.15];',
        '',
        '  return (',
        '    <div className="flex flex-col h-full">',
        '      <div className="flex items-center justify-between mb-4">',
        '        <h2 className="text-xl font-bold text-[#1B2A6B]">Rastreo de Flotas en Tiempo Real</h2>',
        '        <div className="flex items-center gap-4">',
        '          <span className={"flex items-center gap-2 text-sm font-semibold px-3 py-1 rounded-full " + (connected ? "bg-green-100 text-green-700" : "bg-red-100 text-red-700")}>',
        '            <span className={"w-2 h-2 rounded-full " + (connected ? "bg-green-500 animate-pulse" : "bg-red-500")}></span>',
        '            {connected ? "EN VIVO" : "Desconectado"}',
        '          </span>',
        '          <span className="text-sm text-gray-500">{busList.length} buses activos</span>',
        '        </div>',
        '      </div>',
        '      <div className="flex gap-3 mb-4 flex-wrap">',
        '        {busList.map(b => {',
        '          const style = COMPANY_STYLES[b.company] || { bg: "#555", accent: "#fff", label: "BUS" };',
        '          return (',
        '            <div key={b.bus_id} className="flex items-center gap-2 bg-white rounded-xl px-3 py-2 shadow-sm border border-gray-100">',
        '              <div style={{ width: 32, height: 32, borderRadius: 6, background: style.bg, display: "flex", alignItems: "center", justifyContent: "center", color: style.accent, fontWeight: "bold", fontSize: 11 }}>',
        '                {style.label}',
        '              </div>',
        '              <div>',
        '                <p className="font-semibold text-[#1B2A6B] text-xs">{b.company}</p>',
        '                <p className="text-gray-400 text-xs">{b.plate} · {b.speed_kmh} km/h</p>',
        '              </div>',
        '              <span className={"text-xs px-2 py-0.5 rounded-full font-semibold ml-1 " + (b.status === "en_ruta" ? "bg-green-100 text-green-700" : "bg-gray-100 text-gray-500")}>',
        '                {b.status}',
        '              </span>',
        '            </div>',
        '          );',
        '        })}',
        '      </div>',
        '      <div className="flex gap-3 mb-4">',
        '        {Object.entries(COMPANY_STYLES).map(([name, s]) => (',
        '          <div key={name} className="flex items-center gap-2 text-xs text-gray-500">',
        '            <div style={{ width: 14, height: 14, borderRadius: s.shape === "circle" ? "50%" : s.shape === "diamond" ? 2 : 3, background: s.bg, border: 2px solid  }}></div>',
        '            {name}',
        '          </div>',
        '        ))}',
        '      </div>',
        '      <div className="flex-1 rounded-xl overflow-hidden shadow-lg border border-gray-200" style={{ minHeight: 500 }}>',
        '        <MapContainer center={center} zoom={7} style={{ height: "100%", width: "100%", minHeight: 500 }}>',
        '          <TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>',
        '          {busList.map(b => <BusMarker key={b.bus_id} bus={b}/>)}',
        '        </MapContainer>',
        '      </div>',
        '    </div>',
        '  );',
        '}',
    ]) + '\n')
print('OK: TrackingMap.jsx actualizado')