with open('src/components/Navbar.jsx', 'w', encoding='utf-8') as f:
    f.write(
'import { Bus, LayoutDashboard, Map, Users, BarChart3, Calendar } from ' + chr(39) + 'lucide-react' + chr(39) + ';\n'
'\n'
'const NAV_ITEMS = [\n'
'  { id: ' + chr(39) + 'mapa' + chr(39) + ', label: ' + chr(39) + 'Mapa en Vivo' + chr(39) + ', icon: Map },\n'
'  { id: ' + chr(39) + 'empresas' + chr(39) + ', label: ' + chr(39) + 'Empresas' + chr(39) + ', icon: Bus },\n'
'  { id: ' + chr(39) + 'horarios' + chr(39) + ', label: ' + chr(39) + 'Horarios' + chr(39) + ', icon: Calendar },\n'
'  { id: ' + chr(39) + 'manifiesto' + chr(39) + ', label: ' + chr(39) + 'Manifiesto' + chr(39) + ', icon: Users },\n'
'  { id: ' + chr(39) + 'reportes' + chr(39) + ', label: ' + chr(39) + 'Reportes' + chr(39) + ', icon: BarChart3 },\n'
'];\n'
'\n'
'export default function Navbar({ active, onNav }) {\n'
'  return (\n'
'    <div className=' + chr(34) + 'bg-[#1B2A6B] text-white h-screen w-64 flex flex-col fixed left-0 top-0' + chr(34) + '>\n'
'      <div className=' + chr(34) + 'p-6 border-b border-blue-800' + chr(34) + '>\n'
'        <div className=' + chr(34) + 'flex items-center gap-3' + chr(34) + '>\n'
'          <Bus size={32} className=' + chr(34) + 'text-[#D4AF37]' + chr(34) + '/>\n'
'          <div>\n'
'            <p className=' + chr(34) + 'font-bold text-lg' + chr(34) + '>Bolivia Bus</p>\n'
'            <p className=' + chr(34) + 'text-xs text-blue-300' + chr(34) + '>Panel Administrativo</p>\n'
'          </div>\n'
'        </div>\n'
'      </div>\n'
'      <nav className=' + chr(34) + 'flex-1 p-4' + chr(34) + '>\n'
'        {NAV_ITEMS.map(item => (\n'
'          <button key={item.id} onClick={() => onNav(item.id)}\n'
'            className={' + chr(34) + 'w-full flex items-center gap-3 px-4 py-3 rounded-xl mb-1 transition-all text-left ' + chr(34) + ' +\n'
'              (active === item.id ? ' + chr(39) + 'bg-white text-[#1B2A6B] font-semibold' + chr(39) + ' : ' + chr(39) + 'text-blue-200 hover:bg-blue-800' + chr(39) + ')}>\n'
'            <item.icon size={18}/>\n'
'            {item.label}\n'
'          </button>\n'
'        ))}\n'
'      </nav>\n'
'      <div className=' + chr(34) + 'p-4 border-t border-blue-800 text-xs text-blue-400' + chr(34) + '>\n'
'        <p>Terminal de Bolivia</p>\n'
'        <p className=' + chr(34) + 'text-[#D4AF37]' + chr(34) + '>Sistema v1.0.0</p>\n'
'      </div>\n'
'    </div>\n'
'  );\n'
'}\n'
    )
print('OK: Navbar.jsx')